CREATE DATABASE IF NOT EXISTS chat_app_v2 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE chat_app_v2;
CREATE TABLE users (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(50) NOT NULL UNIQUE,
 password_hash VARCHAR(60) NOT NULL, role VARCHAR(10) NOT NULL DEFAULT 'USER',
 is_online BOOLEAN NOT NULL DEFAULT FALSE, last_seen TIMESTAMP NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CHECK (role IN ('USER','ADMIN'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE chat_groups (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(80) NOT NULL,
 created_by BIGINT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE group_members (
 group_id BIGINT NOT NULL, user_id BIGINT NOT NULL, role VARCHAR(10) NOT NULL DEFAULT 'MEMBER',
 joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(group_id,user_id),
 FOREIGN KEY (group_id) REFERENCES chat_groups(id) ON DELETE CASCADE,
 FOREIGN KEY (user_id) REFERENCES users(id), CHECK (role IN ('ADMIN','MEMBER'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE messages (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, sender_id BIGINT NOT NULL, receiver_id BIGINT NOT NULL,
 message TEXT NOT NULL, status VARCHAR(10) NOT NULL DEFAULT 'SENT',
 sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, delivered_at TIMESTAMP NULL, seen_at TIMESTAMP NULL,
 FOREIGN KEY (sender_id) REFERENCES users(id), FOREIGN KEY (receiver_id) REFERENCES users(id),
 CHECK (status IN ('SENT','DELIVERED','SEEN')),
 INDEX idx_conversation(sender_id,receiver_id,id), INDEX idx_pending(receiver_id,status,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE group_messages (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, group_id BIGINT NOT NULL, sender_id BIGINT NOT NULL,
 message TEXT NOT NULL, sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (group_id) REFERENCES chat_groups(id) ON DELETE CASCADE,
 FOREIGN KEY (sender_id) REFERENCES users(id), INDEX idx_group(group_id,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE attachments (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, message_id BIGINT UNIQUE NULL, group_message_id BIGINT UNIQUE NULL,
 file_name VARCHAR(160) NOT NULL, file_path VARCHAR(80) NOT NULL UNIQUE,
 file_size BIGINT NOT NULL, content_type VARCHAR(120) NOT NULL,
 FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE,
 FOREIGN KEY (group_message_id) REFERENCES group_messages(id) ON DELETE CASCADE,
 CHECK ((message_id IS NULL) <> (group_message_id IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO chat_groups(id,name,created_by) VALUES(1,'Community',NULL);
